// Top 100 high-frequency English words with definitions and examples
// Source: Oxford 3000 / GSL (General Service List)
export const HIGH_FREQUENCY_WORDS = [
  { word: 'ability', definition: 'The power or skill to do something', example: 'She has the ability to solve problems quickly.' },
  { word: 'accept', definition: 'To agree to receive or take something offered', example: 'He accepted the job offer with enthusiasm.' },
  { word: 'account', definition: 'A report or description of an event; or a financial record', example: 'She gave a detailed account of the accident.' },
  { word: 'achieve', definition: 'To succeed in doing or reaching something difficult', example: 'Hard work helped him achieve his dreams.' },
  { word: 'action', definition: 'The process of doing something to achieve a result', example: 'The government took action to fix the problem.' },
  { word: 'actually', definition: 'Used to emphasize what is really true', example: 'I thought it would be boring, but it was actually fun.' },
  { word: 'address', definition: 'To speak to someone; or the place where someone lives', example: 'She addressed the crowd with confidence.' },
  { word: 'advance', definition: 'To move forward or make progress', example: 'Technology continues to advance rapidly.' },
  { word: 'affect', definition: 'To have an influence on someone or something', example: 'Stress can negatively affect your health.' },
  { word: 'agree', definition: 'To have the same opinion as someone else', example: 'We all agreed on the best solution.' },
  { word: 'allow', definition: 'To let someone do something or let something happen', example: 'The teacher allowed students to use dictionaries.' },
  { word: 'already', definition: 'Before the present time or earlier than expected', example: 'By noon, she had already finished the report.' },
  { word: 'although', definition: 'In spite of the fact that; even though', example: 'Although it rained, we still enjoyed the trip.' },
  { word: 'always', definition: 'At all times; on every occasion', example: 'He always arrives on time for meetings.' },
  { word: 'apply', definition: 'To make a formal request; or to put something into practice', example: 'She applied for a scholarship at the university.' },
  { word: 'approach', definition: 'A way of dealing with something; to come near', example: 'We need a fresh approach to solve this issue.' },
  { word: 'area', definition: 'A region or part of a place; a subject or field', example: 'This area of the city is very peaceful.' },
  { word: 'argue', definition: 'To give reasons for or against something; to disagree', example: 'They argued about the best route to take.' },
  { word: 'around', definition: 'On all sides of; approximately; in the area of', example: 'There were trees around the old house.' },
  { word: 'ask', definition: 'To say something as a question; to request', example: 'She asked a thoughtful question in class.' },
  { word: 'attempt', definition: 'An effort to do something; to try', example: 'He made his first attempt to climb the mountain.' },
  { word: 'avoid', definition: 'To stay away from someone or something', example: 'Try to avoid eating too much sugar.' },
  { word: 'aware', definition: 'Having knowledge or understanding of something', example: 'She was aware of the risks before deciding.' },
  { word: 'become', definition: 'To start to be something; to grow or develop into', example: 'He worked hard to become a skilled programmer.' },
  { word: 'begin', definition: 'To start doing or happening', example: 'The meeting will begin at nine o\'clock.' },
  { word: 'believe', definition: 'To accept that something is true', example: 'I believe that honesty is the best policy.' },
  { word: 'benefit', definition: 'An advantage or profit; to receive an advantage', example: 'Regular exercise has many health benefits.' },
  { word: 'better', definition: 'Of a higher quality or more suitable', example: 'Practice makes you better at any skill.' },
  { word: 'body', definition: 'The physical structure of a person or animal', example: 'A healthy body supports a healthy mind.' },
  { word: 'break', definition: 'To separate into pieces; a pause or rest', example: 'Let\'s take a short break before continuing.' },
  { word: 'bring', definition: 'To carry or take someone or something to a place', example: 'Please bring your notebook to every class.' },
  { word: 'build', definition: 'To construct something; to develop or increase', example: 'They plan to build a new school here.' },
  { word: 'business', definition: 'The activity of making money by producing or buying things', example: 'She started her own business at age thirty.' },
  { word: 'call', definition: 'To use a phone; to name; to ask someone to come', example: 'Call me if you need any help at all.' },
  { word: 'cause', definition: 'The reason why something happens; to make something happen', example: 'Pollution is a major cause of climate change.' },
  { word: 'certain', definition: 'Confident and sure; particular and known', example: 'I am certain that this is the correct answer.' },
  { word: 'change', definition: 'To make or become different; a difference', example: 'Small habits can lead to big life changes.' },
  { word: 'character', definition: 'The qualities that make a person unique; a person in a story', example: 'Her kind character made everyone love her.' },
  { word: 'choose', definition: 'To select from a number of possibilities', example: 'You can choose any book from the shelf.' },
  { word: 'clear', definition: 'Easy to understand; transparent; free from doubt', example: 'His explanation was very clear and helpful.' },
  { word: 'close', definition: 'Near in space, time, or relationship; to shut', example: 'Please close the window before you leave.' },
  { word: 'common', definition: 'Happening or found often; shared by many people', example: 'Coffee is a common drink around the world.' },
  { word: 'community', definition: 'A group of people living in the same area or sharing interests', example: 'Our community organizes events every month.' },
  { word: 'compare', definition: 'To examine the similarities and differences', example: 'Let\'s compare the two plans carefully.' },
  { word: 'complete', definition: 'Having all parts; to finish something', example: 'She was the first to complete the marathon.' },
  { word: 'concern', definition: 'A worry or interest; to be relevant or important', example: 'Environmental pollution is a global concern.' },
  { word: 'condition', definition: 'The state that something is in; a requirement', example: 'The car is in excellent condition.' },
  { word: 'consider', definition: 'To think carefully about something', example: 'Consider all options before making a decision.' },
  { word: 'continue', definition: 'To keep happening or doing without stopping', example: 'Please continue reading from page ten.' },
  { word: 'control', definition: 'The power to influence; to manage or direct', example: 'Stay calm and stay in control of the situation.' },
  { word: 'create', definition: 'To make or produce something new', example: 'Artists create beauty from simple materials.' },
  { word: 'culture', definition: 'The ideas, customs, and behaviour of a society', example: 'Travel is a great way to learn about culture.' },
  { word: 'current', definition: 'Happening now; a flow of water or electricity', example: 'Stay updated with current events and news.' },
  { word: 'decide', definition: 'To choose after thinking about options', example: 'She decided to study medicine at university.' },
  { word: 'define', definition: 'To explain the meaning of a word or idea', example: 'Can you define the word "ambiguous" for me?' },
  { word: 'describe', definition: 'To say what someone or something is like', example: 'Please describe what happened in your own words.' },
  { word: 'design', definition: 'A plan or drawing; to plan and make something', example: 'The building has a beautiful modern design.' },
  { word: 'develop', definition: 'To grow or cause something to grow and become more advanced', example: 'Children develop language skills very quickly.' },
  { word: 'difference', definition: 'A way in which people or things are not the same', example: 'There is a big difference between want and need.' },
  { word: 'difficult', definition: 'Not easy; needing much effort or skill', example: 'Learning a new language can be difficult at first.' },
  { word: 'discuss', definition: 'To talk about something with others', example: 'We will discuss the results in tomorrow\'s meeting.' },
  { word: 'economy', definition: 'The system of money, industry and trade in a country', example: 'The global economy has grown significantly.' },
  { word: 'education', definition: 'The process of teaching and learning', example: 'Education is the key to a better future.' },
  { word: 'effect', definition: 'A change or result caused by something', example: 'The medicine had an immediate positive effect.' },
  { word: 'effort', definition: 'The energy needed to do something', example: 'Success requires consistent effort every day.' },
  { word: 'environment', definition: 'The natural world; the conditions around you', example: 'We must protect the environment for future generations.' },
  { word: 'especially', definition: 'More than usual; particularly', example: 'I love all sports, especially swimming.' },
  { word: 'example', definition: 'Something that shows what others are like', example: 'She set a great example for younger students.' },
  { word: 'exist', definition: 'To live or be real', example: 'Do you believe that other planets with life exist?' },
  { word: 'expect', definition: 'To think that something will happen', example: 'I expect the results will be ready by Friday.' },
  { word: 'experience', definition: 'Knowledge gained by doing something; an event that happens', example: 'Traveling abroad is a wonderful experience.' },
  { word: 'explain', definition: 'To make something clear and easy to understand', example: 'The teacher explained the concept very well.' },
  { word: 'express', definition: 'To communicate feelings or thoughts', example: 'Art allows people to express themselves freely.' },
  { word: 'fact', definition: 'Something that is true and can be verified', example: 'It is a fact that exercise improves mood.' },
  { word: 'factor', definition: 'One of the things that influences a result', example: 'Diet is an important factor in good health.' },
  { word: 'follow', definition: 'To go after someone; to obey; to understand', example: 'Follow the instructions carefully step by step.' },
  { word: 'force', definition: 'Power or energy; to make someone do something', example: 'The force of the wind broke the old tree.' },
  { word: 'form', definition: 'A type or kind; to make or create; a document to fill in', example: 'Water can exist in the form of ice or steam.' },
  { word: 'future', definition: 'The time that will come after now', example: 'Planning ahead is key to a successful future.' },
  { word: 'general', definition: 'Affecting most people; not specific or detailed', example: 'The general opinion was in favour of the plan.' },
  { word: 'grow', definition: 'To become bigger, more advanced or developed', example: 'Plants grow faster with plenty of sunlight.' },
  { word: 'happen', definition: 'To take place; to occur', example: 'What will happen if we miss the deadline?' },
  { word: 'help', definition: 'To make it easier for someone to do something', example: 'He always helps his neighbours when they need it.' },
  { word: 'history', definition: 'Events of the past; the study of past events', example: 'Learning history helps us avoid old mistakes.' },
  { word: 'human', definition: 'Relating to people; a person', example: 'Human beings are naturally social creatures.' },
  { word: 'idea', definition: 'A thought or suggestion about something', example: 'She had a brilliant idea to improve the process.' },
  { word: 'identify', definition: 'To recognise or name something or someone', example: 'Scientists worked to identify the new species.' },
  { word: 'impact', definition: 'A strong effect or influence on something', example: 'Technology has a huge impact on daily life.' },
  { word: 'important', definition: 'Having great value, meaning or effect', example: 'It is important to stay hydrated every day.' },
  { word: 'improve', definition: 'To become or make something better', example: 'Reading daily will improve your vocabulary.' },
  { word: 'include', definition: 'To have something as part of a whole', example: 'The price includes breakfast and dinner.' },
  { word: 'increase', definition: 'To become or make larger in size or amount', example: 'Exercise can increase your energy levels.' },
  { word: 'indicate', definition: 'To point out or show something', example: 'The data indicates a rise in temperatures.' },
  { word: 'information', definition: 'Facts or knowledge about something', example: 'The internet is a great source of information.' },
  { word: 'involve', definition: 'To include someone or something as a part', example: 'The project involves a lot of teamwork.' },
  { word: 'issue', definition: 'An important topic or problem; to give out officially', example: 'Poverty is a serious issue in many countries.' },
  { word: 'knowledge', definition: 'Facts or skills learned through experience or study', example: 'Knowledge is power in the modern world.' },
  { word: 'language', definition: 'A system of communication used by people', example: 'English is a global language of business.' },
  { word: 'learn', definition: 'To gain knowledge or a skill', example: 'It is never too late to learn something new.' },
]
